### PR TITLE
added cards to kanban board

### PR DESCRIPTION
**Pull request by skvy19**
Eftersom det är första pull req så skulle vara bra om alla kollar igenom

### CODE REVIEW

**Review by spladder87 — APPROVED** [review]
i think it looks good, and its enought for me to start work with my issue and testing out drag and drop on them

**Review by ismb99 — APPROVED** [review]
looks good

**Review by HossamGad — COMMENTED** [review]
Ser bra ut

**Review by MohamedIsse — APPROVED** [review]
Ok

**Pull request closed without merging**
